/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkerIndexRouteImport } from './routes/worker.index'
import { Route as WorkerWellbeingRouteImport } from './routes/worker.wellbeing'
import { Route as WorkerProfileRouteImport } from './routes/worker.profile'
import { Route as WorkerPreviewRouteImport } from './routes/worker.preview'
import { Route as GuideCertificationsRouteImport } from './routes/guide.certifications'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerIndexRoute = WorkerIndexRouteImport.update({
  id: '/worker/',
  path: '/worker/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerWellbeingRoute = WorkerWellbeingRouteImport.update({
  id: '/worker/wellbeing',
  path: '/worker/wellbeing',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerProfileRoute = WorkerProfileRouteImport.update({
  id: '/worker/profile',
  path: '/worker/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerPreviewRoute = WorkerPreviewRouteImport.update({
  id: '/worker/preview',
  path: '/worker/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideCertificationsRoute = GuideCertificationsRouteImport.update({
  id: '/guide/certifications',
  path: '/guide/certifications',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/guide/certifications': typeof GuideCertificationsRoute
  '/worker/preview': typeof WorkerPreviewRoute
  '/worker/profile': typeof WorkerProfileRoute
  '/worker/wellbeing': typeof WorkerWellbeingRoute
  '/worker/': typeof WorkerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/guide/certifications': typeof GuideCertificationsRoute
  '/worker/preview': typeof WorkerPreviewRoute
  '/worker/profile': typeof WorkerProfileRoute
  '/worker/wellbeing': typeof WorkerWellbeingRoute
  '/worker': typeof WorkerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/guide/certifications': typeof GuideCertificationsRoute
  '/worker/preview': typeof WorkerPreviewRoute
  '/worker/profile': typeof WorkerProfileRoute
  '/worker/wellbeing': typeof WorkerWellbeingRoute
  '/worker/': typeof WorkerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/guide/certifications'
    | '/worker/preview'
    | '/worker/profile'
    | '/worker/wellbeing'
    | '/worker/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/guide/certifications'
    | '/worker/preview'
    | '/worker/profile'
    | '/worker/wellbeing'
    | '/worker'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/guide/certifications'
    | '/worker/preview'
    | '/worker/profile'
    | '/worker/wellbeing'
    | '/worker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  GuideCertificationsRoute: typeof GuideCertificationsRoute
  WorkerPreviewRoute: typeof WorkerPreviewRoute
  WorkerProfileRoute: typeof WorkerProfileRoute
  WorkerWellbeingRoute: typeof WorkerWellbeingRoute
  WorkerIndexRoute: typeof WorkerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/': {
      id: '/worker/'
      path: '/worker'
      fullPath: '/worker/'
      preLoaderRoute: typeof WorkerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/wellbeing': {
      id: '/worker/wellbeing'
      path: '/worker/wellbeing'
      fullPath: '/worker/wellbeing'
      preLoaderRoute: typeof WorkerWellbeingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/profile': {
      id: '/worker/profile'
      path: '/worker/profile'
      fullPath: '/worker/profile'
      preLoaderRoute: typeof WorkerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/preview': {
      id: '/worker/preview'
      path: '/worker/preview'
      fullPath: '/worker/preview'
      preLoaderRoute: typeof WorkerPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/certifications': {
      id: '/guide/certifications'
      path: '/guide/certifications'
      fullPath: '/guide/certifications'
      preLoaderRoute: typeof GuideCertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  GuideCertificationsRoute: GuideCertificationsRoute,
  WorkerPreviewRoute: WorkerPreviewRoute,
  WorkerProfileRoute: WorkerProfileRoute,
  WorkerWellbeingRoute: WorkerWellbeingRoute,
  WorkerIndexRoute: WorkerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
