/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as SignupWorkerRouteImport } from './routes/signup.worker'
import { Route as SignupAgentRouteImport } from './routes/signup.agent'
import { Route as AgentWorkersRouteImport } from './routes/agent.workers'
import { Route as AgentWorkersIdRouteImport } from './routes/agent.workers.$id'
import { Route as AgentJobsNewRouteImport } from './routes/agent.jobs.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupWorkerRoute = SignupWorkerRouteImport.update({
  id: '/signup/worker',
  path: '/signup/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupAgentRoute = SignupAgentRouteImport.update({
  id: '/signup/agent',
  path: '/signup/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentWorkersRoute = AgentWorkersRouteImport.update({
  id: '/agent/workers',
  path: '/agent/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentWorkersIdRoute = AgentWorkersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentWorkersRoute,
} as any)
const AgentJobsNewRoute = AgentJobsNewRouteImport.update({
  id: '/agent/jobs/new',
  path: '/agent/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent/workers': typeof AgentWorkersRouteWithChildren
  '/signup/agent': typeof SignupAgentRoute
  '/signup/worker': typeof SignupWorkerRoute
  '/agent/': typeof AgentIndexRoute
  '/agent/jobs/new': typeof AgentJobsNewRoute
  '/agent/workers/$id': typeof AgentWorkersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent/workers': typeof AgentWorkersRouteWithChildren
  '/signup/agent': typeof SignupAgentRoute
  '/signup/worker': typeof SignupWorkerRoute
  '/agent': typeof AgentIndexRoute
  '/agent/jobs/new': typeof AgentJobsNewRoute
  '/agent/workers/$id': typeof AgentWorkersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent/workers': typeof AgentWorkersRouteWithChildren
  '/signup/agent': typeof SignupAgentRoute
  '/signup/worker': typeof SignupWorkerRoute
  '/agent/': typeof AgentIndexRoute
  '/agent/jobs/new': typeof AgentJobsNewRoute
  '/agent/workers/$id': typeof AgentWorkersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent/workers'
    | '/signup/agent'
    | '/signup/worker'
    | '/agent/'
    | '/agent/jobs/new'
    | '/agent/workers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent/workers'
    | '/signup/agent'
    | '/signup/worker'
    | '/agent'
    | '/agent/jobs/new'
    | '/agent/workers/$id'
  id:
    | '__root__'
    | '/'
    | '/agent/workers'
    | '/signup/agent'
    | '/signup/worker'
    | '/agent/'
    | '/agent/jobs/new'
    | '/agent/workers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentWorkersRoute: typeof AgentWorkersRouteWithChildren
  SignupAgentRoute: typeof SignupAgentRoute
  SignupWorkerRoute: typeof SignupWorkerRoute
  AgentIndexRoute: typeof AgentIndexRoute
  AgentJobsNewRoute: typeof AgentJobsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/worker': {
      id: '/signup/worker'
      path: '/signup/worker'
      fullPath: '/signup/worker'
      preLoaderRoute: typeof SignupWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/agent': {
      id: '/signup/agent'
      path: '/signup/agent'
      fullPath: '/signup/agent'
      preLoaderRoute: typeof SignupAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/workers': {
      id: '/agent/workers'
      path: '/agent/workers'
      fullPath: '/agent/workers'
      preLoaderRoute: typeof AgentWorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/workers/$id': {
      id: '/agent/workers/$id'
      path: '/$id'
      fullPath: '/agent/workers/$id'
      preLoaderRoute: typeof AgentWorkersIdRouteImport
      parentRoute: typeof AgentWorkersRoute
    }
    '/agent/jobs/new': {
      id: '/agent/jobs/new'
      path: '/agent/jobs/new'
      fullPath: '/agent/jobs/new'
      preLoaderRoute: typeof AgentJobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentWorkersRouteChildren {
  AgentWorkersIdRoute: typeof AgentWorkersIdRoute
}

const AgentWorkersRouteChildren: AgentWorkersRouteChildren = {
  AgentWorkersIdRoute: AgentWorkersIdRoute,
}

const AgentWorkersRouteWithChildren = AgentWorkersRoute._addFileChildren(
  AgentWorkersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentWorkersRoute: AgentWorkersRouteWithChildren,
  SignupAgentRoute: SignupAgentRoute,
  SignupWorkerRoute: SignupWorkerRoute,
  AgentIndexRoute: AgentIndexRoute,
  AgentJobsNewRoute: AgentJobsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
