/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkerIndexRouteImport } from './routes/worker.index'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as WorkerJobsRouteImport } from './routes/worker.jobs'
import { Route as SignupWorkerRouteImport } from './routes/signup.worker'
import { Route as SignupAgentRouteImport } from './routes/signup.agent'
import { Route as AgentWorkersRouteImport } from './routes/agent.workers'
import { Route as AgentPipelineRouteImport } from './routes/agent.pipeline'
import { Route as WorkerJobsIdRouteImport } from './routes/worker.jobs.$id'
import { Route as AgentWorkersIdRouteImport } from './routes/agent.workers.$id'
import { Route as AgentJobsNewRouteImport } from './routes/agent.jobs.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerIndexRoute = WorkerIndexRouteImport.update({
  id: '/worker/',
  path: '/worker/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerJobsRoute = WorkerJobsRouteImport.update({
  id: '/worker/jobs',
  path: '/worker/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupWorkerRoute = SignupWorkerRouteImport.update({
  id: '/signup/worker',
  path: '/signup/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupAgentRoute = SignupAgentRouteImport.update({
  id: '/signup/agent',
  path: '/signup/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentWorkersRoute = AgentWorkersRouteImport.update({
  id: '/agent/workers',
  path: '/agent/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPipelineRoute = AgentPipelineRouteImport.update({
  id: '/agent/pipeline',
  path: '/agent/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerJobsIdRoute = WorkerJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkerJobsRoute,
} as any)
const AgentWorkersIdRoute = AgentWorkersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentWorkersRoute,
} as any)
const AgentJobsNewRoute = AgentJobsNewRouteImport.update({
  id: '/agent/jobs/new',
  path: '/agent/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent/pipeline': typeof AgentPipelineRoute
  '/agent/workers': typeof AgentWorkersRouteWithChildren
  '/signup/agent': typeof SignupAgentRoute
  '/signup/worker': typeof SignupWorkerRoute
  '/worker/jobs': typeof WorkerJobsRouteWithChildren
  '/agent/': typeof AgentIndexRoute
  '/worker/': typeof WorkerIndexRoute
  '/agent/jobs/new': typeof AgentJobsNewRoute
  '/agent/workers/$id': typeof AgentWorkersIdRoute
  '/worker/jobs/$id': typeof WorkerJobsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent/pipeline': typeof AgentPipelineRoute
  '/agent/workers': typeof AgentWorkersRouteWithChildren
  '/signup/agent': typeof SignupAgentRoute
  '/signup/worker': typeof SignupWorkerRoute
  '/worker/jobs': typeof WorkerJobsRouteWithChildren
  '/agent': typeof AgentIndexRoute
  '/worker': typeof WorkerIndexRoute
  '/agent/jobs/new': typeof AgentJobsNewRoute
  '/agent/workers/$id': typeof AgentWorkersIdRoute
  '/worker/jobs/$id': typeof WorkerJobsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent/pipeline': typeof AgentPipelineRoute
  '/agent/workers': typeof AgentWorkersRouteWithChildren
  '/signup/agent': typeof SignupAgentRoute
  '/signup/worker': typeof SignupWorkerRoute
  '/worker/jobs': typeof WorkerJobsRouteWithChildren
  '/agent/': typeof AgentIndexRoute
  '/worker/': typeof WorkerIndexRoute
  '/agent/jobs/new': typeof AgentJobsNewRoute
  '/agent/workers/$id': typeof AgentWorkersIdRoute
  '/worker/jobs/$id': typeof WorkerJobsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent/pipeline'
    | '/agent/workers'
    | '/signup/agent'
    | '/signup/worker'
    | '/worker/jobs'
    | '/agent/'
    | '/worker/'
    | '/agent/jobs/new'
    | '/agent/workers/$id'
    | '/worker/jobs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent/pipeline'
    | '/agent/workers'
    | '/signup/agent'
    | '/signup/worker'
    | '/worker/jobs'
    | '/agent'
    | '/worker'
    | '/agent/jobs/new'
    | '/agent/workers/$id'
    | '/worker/jobs/$id'
  id:
    | '__root__'
    | '/'
    | '/agent/pipeline'
    | '/agent/workers'
    | '/signup/agent'
    | '/signup/worker'
    | '/worker/jobs'
    | '/agent/'
    | '/worker/'
    | '/agent/jobs/new'
    | '/agent/workers/$id'
    | '/worker/jobs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentPipelineRoute: typeof AgentPipelineRoute
  AgentWorkersRoute: typeof AgentWorkersRouteWithChildren
  SignupAgentRoute: typeof SignupAgentRoute
  SignupWorkerRoute: typeof SignupWorkerRoute
  WorkerJobsRoute: typeof WorkerJobsRouteWithChildren
  AgentIndexRoute: typeof AgentIndexRoute
  WorkerIndexRoute: typeof WorkerIndexRoute
  AgentJobsNewRoute: typeof AgentJobsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/': {
      id: '/worker/'
      path: '/worker'
      fullPath: '/worker/'
      preLoaderRoute: typeof WorkerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/jobs': {
      id: '/worker/jobs'
      path: '/worker/jobs'
      fullPath: '/worker/jobs'
      preLoaderRoute: typeof WorkerJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/worker': {
      id: '/signup/worker'
      path: '/signup/worker'
      fullPath: '/signup/worker'
      preLoaderRoute: typeof SignupWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/agent': {
      id: '/signup/agent'
      path: '/signup/agent'
      fullPath: '/signup/agent'
      preLoaderRoute: typeof SignupAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/workers': {
      id: '/agent/workers'
      path: '/agent/workers'
      fullPath: '/agent/workers'
      preLoaderRoute: typeof AgentWorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/pipeline': {
      id: '/agent/pipeline'
      path: '/agent/pipeline'
      fullPath: '/agent/pipeline'
      preLoaderRoute: typeof AgentPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/jobs/$id': {
      id: '/worker/jobs/$id'
      path: '/$id'
      fullPath: '/worker/jobs/$id'
      preLoaderRoute: typeof WorkerJobsIdRouteImport
      parentRoute: typeof WorkerJobsRoute
    }
    '/agent/workers/$id': {
      id: '/agent/workers/$id'
      path: '/$id'
      fullPath: '/agent/workers/$id'
      preLoaderRoute: typeof AgentWorkersIdRouteImport
      parentRoute: typeof AgentWorkersRoute
    }
    '/agent/jobs/new': {
      id: '/agent/jobs/new'
      path: '/agent/jobs/new'
      fullPath: '/agent/jobs/new'
      preLoaderRoute: typeof AgentJobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentWorkersRouteChildren {
  AgentWorkersIdRoute: typeof AgentWorkersIdRoute
}

const AgentWorkersRouteChildren: AgentWorkersRouteChildren = {
  AgentWorkersIdRoute: AgentWorkersIdRoute,
}

const AgentWorkersRouteWithChildren = AgentWorkersRoute._addFileChildren(
  AgentWorkersRouteChildren,
)

interface WorkerJobsRouteChildren {
  WorkerJobsIdRoute: typeof WorkerJobsIdRoute
}

const WorkerJobsRouteChildren: WorkerJobsRouteChildren = {
  WorkerJobsIdRoute: WorkerJobsIdRoute,
}

const WorkerJobsRouteWithChildren = WorkerJobsRoute._addFileChildren(
  WorkerJobsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentPipelineRoute: AgentPipelineRoute,
  AgentWorkersRoute: AgentWorkersRouteWithChildren,
  SignupAgentRoute: SignupAgentRoute,
  SignupWorkerRoute: SignupWorkerRoute,
  WorkerJobsRoute: WorkerJobsRouteWithChildren,
  AgentIndexRoute: AgentIndexRoute,
  WorkerIndexRoute: WorkerIndexRoute,
  AgentJobsNewRoute: AgentJobsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
