ALTER TABLE public.jobs
  ALTER COLUMN title DROP NOT NULL,
  ALTER COLUMN sector DROP NOT NULL,
  ALTER COLUMN work_pass_type DROP NOT NULL,
  ALTER COLUMN workers_needed DROP NOT NULL,
  ALTER COLUMN min_salary DROP NOT NULL,
  ALTER COLUMN max_salary DROP NOT NULL,
  ALTER COLUMN location DROP NOT NULL,
  ALTER COLUMN contract_duration DROP NOT NULL,
  ALTER COLUMN start_date DROP NOT NULL,
  ALTER COLUMN work_hours DROP NOT NULL,
  ALTER COLUMN description DROP NOT NULL;